Add support for the remote API
hacf-fr/freebox-api pull request #51
Opened 2019-11-06 21:10 UTC by foreign-sub

Add
build_key
send_key
send_macro
set_key
set_player_host

2020-08-30 17:58 UTC, Quentame commented
Need this for a new [Home Assistant](https://github.com/home-assistant/core) feature @SNoof85

2020-08-30 20:25 UTC, SNoof85 commented
@Quentame do you get what's needed to test this ? I have now the Freebox Pop (server/player) then this won't work !

2020-08-31 06:44 UTC, Quentame commented
Yep, Freebox Révolution

2020-08-31 11:07 UTC, Quentame requested changes
Some stuffs can be cleaned

2020-08-31 11:07 UTC, Quentame commented on aiofreepybox/api/remote.py
> +                if r.status == _PL_STATUS and r.content_length == 0:
`_PL_STATUS` const not necessary

2020-08-31 11:07 UTC, Quentame commented on aiofreepybox/api/remote.py
> +        player_id: Optional[int] = None,
```suggestion
        player_id: Optional[int] = _DEFAULT_PL_ID,
```

2020-08-31 11:07 UTC, Quentame commented on aiofreepybox/api/remote.py
> +            f"{_DEFAULT_PL_ID if player_id is None else player_id}{_PL_DOMAIN}"
```suggestion
            self.player_host = f"{_PL_HOST}{player_id}{_PL_DOMAIN}"
```

2020-08-31 11:07 UTC, Quentame commented on aiofreepybox/api/remote.py
> +        self.access_mode = _DEFAULT_ACCESS_MODE if access_m is None else access_m
```suggestion
        self.access_mode = _DEFAULT_ACCESS_MODE if not access_m else access_m
```

2020-08-31 11:07 UTC, Quentame commented on aiofreepybox/api/remote.py
> +        repeat : `int`
or Any

2020-09-12 22:46 UTC, closed without merging